# Generated by Django 5.2.17 on 2026-10-02 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=8)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('timezone_name', models.CharField(max_length=64)),
                ('start_local', models.CharField(max_length=32)),
                ('until_date', models.DateField()),
                ('occurrence_limit', models.PositiveSmallIntegerField(default=52)),
                ('lead_days', models.PositiveSmallIntegerField(default=7)),
                ('next_index', models.PositiveSmallIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=80)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('source_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='tasks.task')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RecurringOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveSmallIntegerField()),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_occurrence', to='tasks.task')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='productivity.recurringtask')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('timer', 'Timer'), ('manual', 'Manual')], max_length=8)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('capped', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='recurringtask',
            index=models.Index(fields=['stopped_at', 'next_run_at'], name='productivity_next_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringtask',
            constraint=models.CheckConstraint(condition=models.Q(('frequency__in', ('weekly', 'monthly'))), name='productivity_frequency_valid'),
        ),
        migrations.AddConstraint(
            model_name='recurringtask',
            constraint=models.CheckConstraint(condition=models.Q(('interval__gte', 1), ('interval__lte', 12)), name='productivity_interval_valid'),
        ),
        migrations.AddConstraint(
            model_name='recurringtask',
            constraint=models.CheckConstraint(condition=models.Q(('occurrence_limit__gte', 1), ('occurrence_limit__lte', 520)), name='productivity_count_valid'),
        ),
        migrations.AddConstraint(
            model_name='recurringtask',
            constraint=models.CheckConstraint(condition=models.Q(('lead_days__lte', 30)), name='productivity_lead_valid'),
        ),
        migrations.AddConstraint(
            model_name='recurringtask',
            constraint=models.UniqueConstraint(condition=models.Q(('stopped_at__isnull', True)), fields=('source_task',), name='productivity_source_one_active'),
        ),
        migrations.AddConstraint(
            model_name='recurringoccurrence',
            constraint=models.UniqueConstraint(fields=('schedule', 'index'), name='productivity_occurrence_unique'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['task', 'cancelled_at'], name='productivity_task_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True), ('ended_at__isnull', True)), fields=('user',), name='productivity_one_active_timer'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('seconds__lte', 86400)), name='productivity_time_max_day'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='productivity_time_ordered'),
        ),
    ]
