# Generated by Django 5.2.17 on 2026-10-02 07:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('university', models.CharField(max_length=120)),
                ('course', models.CharField(max_length=60)),
                ('term', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=3000)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('skills_search', models.CharField(blank=True, editable=False, max_length=1024)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('cooperation', models.CharField(choices=[('online', 'Online'), ('campus', 'On campus'), ('hybrid', 'Hybrid')], default='hybrid', max_length=12)),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('published_at', models.DateTimeField()),
                ('consent_at', models.DateTimeField()),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_reason', models.CharField(blank=True, max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='projects.project')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='recruiting.recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=1500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('decision_reason', models.CharField(blank=True, max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_applications', to=settings.AUTH_USER_MODEL)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruiting.recruitment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('misleading', 'Misleading identity or information'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('resolution', models.TextField(blank=True, max_length=1000)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='recruiting.recruitment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recruitment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['status', 'expires_at'], name='recruitment_open_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('project',), name='one_open_recruitment_per_project'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('capacity__lte', 20)), name='recruitment_valid_capacity'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'recruitment'), name='unique_recruitment_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('recruitment', 'applicant'), name='one_recruitment_application_per_user'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('recruitment', 'reporter'), name='one_open_recruitment_report_per_user'),
        ),
    ]
