# Generated by Django 5.2.17 on 2026-09-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'permissions': [('manage_user_status', 'Can suspend and restore user accounts')]},
        ),
    ]
