# Generated by Django 5.2.17 on 2026-10-01 17:56

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountsecuritythrottle_recoveryemail_user_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collaboration_preference',
            field=models.CharField(blank=True, choices=[('', 'No preference'), ('online', 'Online'), ('in_person', 'In person'), ('hybrid', 'Online and in person')], max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='communication_languages',
            field=models.JSONField(blank=True, default=list, validators=[accounts.validators.validate_languages_list]),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=list, validators=[accounts.validators.validate_skills_list]),
        ),
    ]
