# Generated by Django 5.2.17 on 2026-09-13 10:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=2048)),
                ('agenda', models.TextField(blank=True, max_length=4000)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organised_meetings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project')),
            ],
            options={
                'ordering': ('starts_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('availability_note', models.CharField(blank=True, max_length=500)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['project', 'starts_at'], name='meeting_project_start_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['project', 'cancelled_at'], name='meeting_project_cancel_idx'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='meeting_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['user', 'response'], name='attendance_user_resp_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendance',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='unique_meeting_attendee'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendance',
            constraint=models.CheckConstraint(condition=models.Q(('response__in', ('pending', 'accepted', 'declined'))), name='attendance_valid_response'),
        ),
    ]
