# Generated by Django 5.2.17 on 2026-09-20 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['project', 'archived_at', 'starts_at'], name='meeting_project_archive_idx'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('archived_at__isnull', True), ('cancelled_at__isnull', False), ('ends_at__lte', models.F('archived_at')), _connector='OR'), name='meeting_archive_after_terminal_state'),
        ),
    ]
