# Generated by Django 5.2.17 on 2026-10-01 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_accountsecuritythrottle_recoveryemail_user_closed_at_and_more'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinAttempt',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('window_started_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300)),
                ('checked', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_checklist', to='tasks.task')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('university', 'code'),
            },
        ),
        migrations.CreateModel(
            name='JoinLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.PositiveSmallIntegerField(default=10)),
                ('uses', models.PositiveSmallIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_links', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=12)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='campus.joinlink')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ('due_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=2048)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('tags', models.JSONField(default=list)),
                ('pinned', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='projects.project')),
            ],
            options={
                'ordering': ('-pinned', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubmissionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official_due_at', models.DateTimeField(blank=True, null=True)),
                ('internal_due_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('receipt_url', models.URLField(blank=True, max_length=2048)),
                ('receipt_reference', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_plan', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300)),
                ('checked', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campus.submissionplan')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubmissionConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='campus.submissionplan')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_dependents', to='tasks.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_dependencies', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acceptance', models.TextField(blank=True, max_length=4000)),
                ('official_due_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_url', models.URLField(blank=True, max_length=2048)),
                ('review_state', models.CharField(choices=[('draft', 'draft'), ('requested', 'requested'), ('approved', 'approved'), ('changes_requested', 'changes_requested')], default='draft', max_length=24)),
                ('review_note', models.CharField(blank=True, max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.milestone')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_children', to='tasks.task')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_plan', to='tasks.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=6000)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_agreement', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgreementConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='campus.teamagreement')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.CharField(max_length=120)),
                ('year', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProjectCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.course')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_links', to='projects.project')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.term')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('owner', 'university', 'code'), name='campus_course_unique'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('project', 'user'), name='campus_join_pending_unique'),
        ),
        migrations.AddConstraint(
            model_name='submissionconfirmation',
            constraint=models.UniqueConstraint(fields=('plan', 'user'), name='campus_submission_confirmation_unique'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'depends_on'), name='campus_dependency_unique'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.CheckConstraint(condition=models.Q(('task', models.F('depends_on')), _negated=True), name='campus_dependency_not_self'),
        ),
        migrations.AddConstraint(
            model_name='agreementconfirmation',
            constraint=models.UniqueConstraint(fields=('agreement', 'user'), name='campus_agreement_confirmation_unique'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('owner', 'university', 'year', 'name'), name='campus_term_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectcourse',
            constraint=models.UniqueConstraint(fields=('project', 'course', 'term'), name='campus_project_course_unique'),
        ),
    ]
