# Generated by Django 5.2.17 on 2026-10-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelink',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
