# Generated by Django 5.2.17 on 2026-10-01 17:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_alter_resourcelink_tags'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskplan',
            name='estimate_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='taskplan',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='taskplan',
            constraint=models.CheckConstraint(condition=models.Q(('estimate_hours__isnull', True), models.Q(('estimate_hours__gte', 0), ('estimate_hours__lte', 1000)), _connector='OR'), name='campus_estimate_valid_range'),
        ),
    ]
