# Generated by Django 5.2.17 on 2026-10-02 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=16)),
                ('source_namespace', models.CharField(max_length=80)),
                ('timezone_name', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('imported_count', models.PositiveSmallIntegerField(default=0)),
                ('skipped_count', models.PositiveSmallIntegerField(default=0)),
                ('rows', models.JSONField(default=list)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ImportedAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=16)),
                ('source_namespace', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=160)),
                ('source_row', models.PositiveSmallIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning_exchange.importbatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='learning_import', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='ImportPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=16)),
                ('source_namespace', models.CharField(max_length=80)),
                ('timezone_name', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('rows', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_exchange.importbatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('project', 'content_hash'), name='learning_batch_unique'),
        ),
        migrations.AddConstraint(
            model_name='importedassignment',
            constraint=models.UniqueConstraint(fields=('project', 'source', 'source_namespace', 'source_id'), name='learning_source_unique'),
        ),
    ]
