# Generated by Django 5.2.17 on 2026-09-13 07:11

import activity.models
import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('project_archived', 'Project archived'), ('invitation_created', 'Invitation created'), ('invitation_declined', 'Invitation declined'), ('invitation_cancelled', 'Invitation cancelled'), ('invitation_expired', 'Invitation expired'), ('member_joined', 'Member joined'), ('member_role_changed', 'Member role changed'), ('member_removed', 'Member removed'), ('ownership_transferred', 'Ownership transferred'), ('task_created', 'Task created'), ('task_updated', 'Task updated'), ('task_archived', 'Task archived'), ('task_assignees_changed', 'Task assignees changed'), ('task_assigned', 'Task assigned'), ('task_unassigned', 'Task unassigned'), ('task_status_changed', 'Task status changed'), ('comment_created', 'Comment created'), ('comment_edited', 'Comment edited'), ('comment_deleted', 'Comment deleted'), ('comment_moderated', 'Comment moderated'), ('comment_reported', 'Comment reported'), ('meeting_created', 'Meeting created'), ('meeting_updated', 'Meeting updated'), ('meeting_cancelled', 'Meeting cancelled'), ('meeting_rsvp', 'Meeting RSVP changed'), ('export_requested', 'Export requested'), ('export_ready', 'Export ready'), ('export_failed', 'Export failed')], max_length=40)),
                ('target_type', models.CharField(blank=True, choices=[('project', 'Project'), ('membership', 'Project membership'), ('invitation', 'Project invitation'), ('task', 'Task'), ('comment', 'Task comment'), ('meeting', 'Meeting'), ('attendance', 'Meeting attendance'), ('export', 'Export job')], max_length=24)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[activity.models.validate_metadata])),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='projects.project')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], max_length=8)),
                ('range_start', models.DateField()),
                ('range_end', models.DateField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=16)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('invitation', 'Invitation'), ('task_assignment', 'Task assignment'), ('comment_mention', 'Comment mention'), ('meeting_change', 'Meeting change')], max_length=24)),
                ('target_url', models.CharField(max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('source_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='activity.activityevent')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SiteAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_disabled', 'User disabled'), ('user_enabled', 'User enabled'), ('comment_moderated', 'Comment moderated'), ('content_report_resolved', 'Content report resolved')], max_length=32)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[activity.models.validate_metadata])),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['project', 'occurred_at'], name='activity_project_time_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['actor', 'occurred_at'], name='activity_actor_time_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['project', 'event_type'], name='activity_project_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_id__isnull', True), ('target_type', '')), models.Q(models.Q(('target_type', ''), _negated=True), ('target_id__isnull', False)), _connector='OR'), name='activity_target_pair_complete'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['project', 'created_at'], name='export_project_time_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['status', 'expires_at'], name='export_status_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(condition=models.Q(('range_end__gte', models.F('range_start'))), name='export_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(condition=models.Q(('range_end__lte', django.db.models.expressions.CombinedExpression(models.F('range_start'), '+', models.Value(datetime.timedelta(days=366))))), name='export_range_at_most_366_days'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ready'), _negated=True), models.Q(models.Q(('storage_key', ''), _negated=True), ('expires_at__isnull', False), ('completed_at__isnull', False)), _connector='OR'), name='ready_export_has_file_and_expiry'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='notification_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'source_event'), name='unique_notification_recipient_event'),
        ),
        migrations.AddIndex(
            model_name='siteauditevent',
            index=models.Index(fields=['actor', 'occurred_at'], name='site_audit_actor_time_idx'),
        ),
        migrations.AddIndex(
            model_name='siteauditevent',
            index=models.Index(fields=['target_type', 'target_id'], name='site_audit_target_idx'),
        ),
    ]
