# Generated by Django 5.2.17 on 2026-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('project_archived', 'Project archived'), ('invitation_created', 'Invitation created'), ('invitation_declined', 'Invitation declined'), ('invitation_cancelled', 'Invitation cancelled'), ('invitation_expired', 'Invitation expired'), ('member_joined', 'Member joined'), ('member_role_changed', 'Member role changed'), ('member_removed', 'Member removed'), ('ownership_transferred', 'Ownership transferred'), ('task_created', 'Task created'), ('task_updated', 'Task updated'), ('task_archived', 'Task archived'), ('task_assignees_changed', 'Task assignees changed'), ('task_assigned', 'Task assigned'), ('task_unassigned', 'Task unassigned'), ('task_status_changed', 'Task status changed'), ('comment_created', 'Comment created'), ('comment_edited', 'Comment edited'), ('comment_deleted', 'Comment deleted'), ('comment_moderated', 'Comment moderated'), ('comment_reported', 'Comment reported'), ('meeting_created', 'Meeting created'), ('meeting_updated', 'Meeting updated'), ('meeting_cancelled', 'Meeting cancelled'), ('meeting_archived', 'Meeting archived'), ('meeting_rsvp', 'Meeting RSVP changed'), ('task_reminder_sent', 'Task reminder sent'), ('meeting_reminder_sent', 'Meeting reminder sent'), ('export_requested', 'Export requested'), ('export_ready', 'Export ready'), ('export_failed', 'Export failed')], max_length=40),
        ),
    ]
