import { useEffect, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { coordinationApi, type AvailabilitySlot, type MeetingRecord, type Participant } from "../api/coordination";
import { accountApi, membershipApi, projectApi } from "../api/resources";
import { errorMessage } from "../api/client";
import { formatDate } from "../app/format";
import { Button, ConfirmAction, EmptyState, ErrorState, Field, Loading, Panel } from "../components/UI";
import "../coordination.css";
import DraftForm from "../components/DraftForm";

const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const minuteText = (minute: number) => `${String(Math.floor(minute / 60)).padStart(2, "0")}:${String(minute % 60).padStart(2, "0")}`;
const readMinute = (value: string) => Number(value.slice(0, 2)) * 60 + Number(value.slice(3, 5));
const instant = (value: FormDataEntryValue | null) => value ? new Date(String(value)).toISOString() : null;
function monday() {
  const date = new Date(); date.setDate(date.getDate() - (date.getDay() + 6) % 7);
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}

function ParticipantPicker({ members, selected, onChange, disabled = false }: { members: { id: string; display_name: string }[]; selected: Participant[]; onChange: (value: Participant[]) => void; disabled?: boolean }) {
  return <fieldset className="coord-participants"><legend>Participants</legend>{members.map((member) => {
    const current = selected.find((entry) => entry.user_id === member.id);
    return <div className="coord-participant" key={member.id}><label><input type="checkbox" checked={Boolean(current)} disabled={disabled} onChange={(event) => onChange(event.target.checked ? [...selected, { user_id: member.id, required: true }] : selected.filter((entry) => entry.user_id !== member.id))} /> {member.display_name}</label>{current && <label><input type="checkbox" checked={current.required} disabled={disabled} onChange={(event) => onChange(selected.map((entry) => entry.user_id === member.id ? { ...entry, required: event.target.checked } : entry))} /> Required</label>}</div>;
  })}</fieldset>;
}

export default function CoordinationPage() {
  const { projectId = "" } = useParams();
  const client = useQueryClient();
  const [week, setWeek] = useState(monday);
  const [slots, setSlots] = useState<AvailabilitySlot[]>([]);
  const [availabilityDirty, setAvailabilityDirty] = useState(false);
  const [participants, setParticipants] = useState<Participant[]>([]);
  const [candidates, setCandidates] = useState<{ starts_at: string; ends_at: string }[]>([]);
  const [selected, setSelected] = useState("");
  const [pollPage, setPollPage] = useState(1);
  const [meetingPage, setMeetingPage] = useState(1);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const me = useQuery({ queryKey: ["me"], queryFn: accountApi.me });
  const project = useQuery({ queryKey: ["project", projectId], queryFn: () => projectApi.get(projectId), enabled: Boolean(projectId) });
  const memberships = useQuery({ queryKey: ["memberships", projectId], queryFn: () => membershipApi.list(projectId), enabled: Boolean(projectId) });
  const availability = useQuery({ queryKey: ["coord-availability", projectId, week], queryFn: () => coordinationApi.availability(projectId, week), enabled: Boolean(projectId && week) });
  const polls = useQuery({ queryKey: ["coord-polls", projectId, pollPage], queryFn: () => coordinationApi.polls(projectId, pollPage), enabled: Boolean(projectId) });
  const meetings = useQuery({ queryKey: ["coord-records", projectId, meetingPage], queryFn: () => coordinationApi.meetingRecords(projectId, meetingPage), enabled: Boolean(projectId) });
  const selectedMeeting = useQuery({ queryKey: ["coord-record", projectId, selected], queryFn: () => coordinationApi.meetingRecord(selected), enabled: Boolean(selected) });
  const operation = useMutation({ mutationFn: (action: () => Promise<unknown>) => action(), onSuccess: async () => { setError(""); await Promise.all([client.invalidateQueries({ queryKey: ["coord-polls", projectId] }), client.invalidateQueries({ queryKey: ["coord-records", projectId] }), client.invalidateQueries({ queryKey: ["coord-record", projectId] }), client.invalidateQueries({ queryKey: ["coord-availability", projectId] }), client.invalidateQueries({ queryKey: ["calendar"] }), client.invalidateQueries({ queryKey: ["tasks", projectId] }), client.invalidateQueries({ queryKey: ["meetings", projectId] }), client.invalidateQueries({ queryKey: ["coord-evidence", projectId] })]); }, onError: (value) => { setNotice(""); setError(errorMessage(value)); } });
  useEffect(() => { setSlots([]); setAvailabilityDirty(false); setParticipants([]); setCandidates([]); setSelected(""); setPollPage(1); setMeetingPage(1); setError(""); setNotice(""); }, [projectId]);
  useEffect(() => { if (availability.data && !availabilityDirty) setSlots(availability.data.mine.slots); }, [availability.data, availabilityDirty]);
  const busy = operation.isPending;
  const archived = Boolean(project.data?.archived_at);
  const members = memberships.data?.results.map((row) => row.user) ?? [];
  const record = selectedMeeting.data ?? meetings.data?.meetings.find((row) => row.id === selected);
  const doAction = (action: () => Promise<unknown>, message: string) => operation.mutate(async () => { const result = await action(); setNotice(message); return result; });
  const addBlock = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form);
    setSlots((values) => [...values, { weekday: Number(data.get("weekday")), start_minute: readMinute(String(data.get("start"))), end_minute: readMinute(String(data.get("end"))) }]); setAvailabilityDirty(true);
  };
  const addCandidate = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form);
    try { const starts_at = instant(data.get("start")); const ends_at = instant(data.get("end")); if (starts_at && ends_at) setCandidates((values) => [...values, { starts_at, ends_at }]); } catch (value) { setError(errorMessage(value)); }
  };
  const createPoll = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form);
    doAction(async () => { await coordinationApi.createPoll({ project: projectId, title: String(data.get("title")), agenda: String(data.get("agenda")), location: String(data.get("location")), participants, options: candidates }); form.reset(); setParticipants([]); setCandidates([]); }, "Scheduling poll created. Participants can now vote on each candidate.");
  };
  if (project.isLoading || me.isLoading || memberships.isLoading) return <Loading label="Loading team coordination…" />;
  if (project.error || me.error || memberships.error) return <ErrorState error={project.error ?? me.error ?? memberships.error} retry={() => { void project.refetch(); void me.refetch(); void memberships.refetch(); }} />;
  return <div className="page-stack coordination-page"><header className="page-heading"><div><p className="eyebrow">{project.data?.name}</p><h1>Team coordination</h1><p>Find shared time, decide on a meeting, record outcomes and turn actions into real tasks.</p></div><Link className="button button--secondary" to={`/app/calendar/?project=${projectId}`}>Calendar</Link></header>
    {error && <p className="form-error" role="alert">{error}</p>}{notice && <p className="success-message" role="status">{notice}</p>}{archived && <p role="status">This project is archived. All coordination records are read-only.</p>}
    <Panel><h2>Weekly availability</h2><p>Share free time with this project only. Your blocks repeat weekly; the grid converts everyone's blocks into your profile time zone.</p><Field label="Week beginning (Monday)"><input type="date" value={week} onChange={(event) => setWeek(event.target.value)} required /></Field>
      {availability.isLoading ? <Loading label="Loading shared time…" /> : availability.error ? <ErrorState error={availability.error} retry={() => void availability.refetch()} /> : <>
        <p className="muted">{availability.data?.basis} Grid time zone: {availability.data?.time_zone}. {availability.data?.members.filter((member) => member.shared_availability).length} / {availability.data?.members.length} members have shared blocks.</p>
        <div className="coord-heatmap-scroll"><table className="coord-heatmap"><caption>Available member count for each half-hour; “All” means every current active member has shared availability for that block.</caption><thead><tr><th scope="col">Time</th>{days.map((day) => <th scope="col" key={day}>{day.slice(0, 3)}</th>)}</tr></thead><tbody>{Array.from({ length: 48 }, (_, index) => index * 30).map((minute) => <tr key={minute}><th scope="row">{minuteText(minute)}</th>{days.map((_, day) => {
          const cell = availability.data?.cells.find((item) => item.weekday === day && item.start_minute === minute);
          const total = availability.data?.members.length ?? 0;
          const names = availability.data?.members.filter((member) => cell?.available_ids.includes(member.id)).map((member) => member.display_name).join(", ") ?? "";
          return <td key={day} className={cell?.available_count === total && total > 0 ? "coord-heatmap-all" : cell?.available_count ? "coord-heatmap-some" : "coord-heatmap-none"}><span title={names || "No reported free time"}>{cell?.available_count === total && total > 0 ? `All (${total})` : `${cell?.available_count ?? 0}/${total}`}</span><span className="sr-only">{names}</span></td>;
        })}</tr>)}</tbody></table></div>
        {!archived && <details className="coord-editor"><summary>Edit my recurring free time</summary><p>Blocks use {availability.data?.mine.time_zone ?? me.data?.profile.time_zone}. Saving an empty list clears your shared free time.</p><form className="form-grid" onSubmit={addBlock}><Field label="Day"><select name="weekday">{days.map((label, index) => <option value={index} key={label}>{label}</option>)}</select></Field><Field label="From"><input type="time" name="start" step={1800} required defaultValue="09:00" /></Field><Field label="Until"><input type="time" name="end" step={1800} required defaultValue="10:00" /></Field><Button disabled={busy || slots.length >= 100}>Add free-time block</Button></form><ul className="coord-blocks">{slots.map((slot, index) => <li key={`${slot.weekday}-${slot.start_minute}-${index}`}>{days[slot.weekday]} {minuteText(slot.start_minute)}–{minuteText(slot.end_minute)} <Button disabled={busy} variant="quiet" onClick={() => { setSlots((values) => values.filter((_, item) => item !== index)); setAvailabilityDirty(true); }}>Remove</Button></li>)}</ul><Button disabled={busy || !availabilityDirty} onClick={() => doAction(async () => { await coordinationApi.saveAvailability(projectId, availability.data?.mine.time_zone ?? me.data?.profile.time_zone ?? "UTC", slots); setAvailabilityDirty(false); }, "Your recurring free time was saved.")}>Save availability</Button></details>}
      </>}
    </Panel>
    <Panel><h2>Meeting time polls</h2><p>Required participants must mark a candidate available before it can become a meeting. “If needed” and no response do not count as agreement.</p>
      {!archived && <details className="coord-editor"><summary>Create a time poll</summary><form onSubmit={createPoll} className="form-stack"><Field label="Meeting title"><input name="title" minLength={3} maxLength={120} required /></Field><Field label="Agenda"><textarea name="agenda" maxLength={4000} rows={3} /></Field><Field label="Location or meeting URL"><input name="location" maxLength={2048} /></Field><ParticipantPicker members={members} selected={participants} onChange={setParticipants} disabled={busy} /><p>{candidates.length} candidate times added. Add 2–12 times below, then create the poll.</p><ul>{candidates.map((candidate, index) => <li key={index}>{formatDate(candidate.starts_at)} – {formatDate(candidate.ends_at)} <Button type="button" variant="quiet" disabled={busy} onClick={() => setCandidates((values) => values.filter((_, candidateIndex) => candidateIndex !== index))}>Remove time</Button></li>)}</ul><Button disabled={busy || candidates.length < 2 || participants.length < 1}>Create poll</Button></form><form className="form-grid" onSubmit={addCandidate}><Field label="Candidate starts (your device time zone)"><input name="start" type="datetime-local" required /></Field><Field label="Candidate ends"><input name="end" type="datetime-local" required /></Field><Button disabled={busy || candidates.length >= 12}>Add candidate</Button></form></details>}
      {polls.isLoading ? <Loading label="Loading polls…" /> : polls.error ? <ErrorState error={polls.error} retry={() => void polls.refetch()} /> : !polls.data?.polls.length ? <EmptyState title="No time polls">Create two or more candidate times to start a team vote.</EmptyState> : <div className="coord-list">{polls.data.polls.map((poll) => <article className="coord-card" key={poll.id}><h3>{poll.title}</h3><p>{poll.agenda}</p><p>{poll.closed_at ? (poll.meeting_id ? "Closed · meeting scheduled" : "Closed without a meeting") : "Open poll"}</p><p>{poll.participants.map((entry) => `${entry.display_name}${entry.required ? " (required)" : " (optional)"}${entry.active ? "" : " (former member)"}`).join(" · ")}</p>{poll.participants.some((entry) => !entry.active) && !poll.closed_at && <p role="status">A participant has left the project. Create a replacement poll for the current team.</p>}<div className="coord-options">{poll.options.map((option) => { const mine = option.votes.find((vote) => vote.user_id === me.data?.user.id)?.response; return <div key={option.id} className="coord-option"><strong>{formatDate(option.starts_at)} – {formatDate(option.ends_at)}</strong><p>{poll.participants.map((entry) => `${entry.display_name}: ${option.votes.find((vote) => vote.user_id === entry.user_id)?.response ?? "not voted"}`).join(" · ")}</p>{!poll.closed_at && poll.can_vote && <div className="form-actions">{(["yes", "maybe", "no"] as const).map((response) => <Button aria-pressed={mine === response} variant={mine === response ? "primary" : "secondary"} disabled={busy} key={response} onClick={() => doAction(() => coordinationApi.vote(option.id, response), "Your vote was saved.")}>{response === "yes" ? "Available" : response === "maybe" ? "If needed" : "Unavailable"}</Button>)}</div>}{!poll.closed_at && poll.can_manage && <ConfirmAction busy={busy} triggerLabel="Schedule this time" triggerVariant="secondary" confirmLabel="Close poll & create meeting" message="Close voting and create a real project meeting at this time? Every required member must have voted available." onConfirm={() => doAction(async () => { const meeting = await coordinationApi.closePoll(poll.id, option.id); setSelected(meeting.id); }, "Poll closed and real meeting scheduled.")} />}</div>; })}</div>{!poll.closed_at && poll.can_manage && <ConfirmAction busy={busy} triggerLabel="Close without a meeting" confirmLabel="Close poll" message="Close this poll without scheduling a meeting? Votes will be retained." onConfirm={() => doAction(() => coordinationApi.cancelPoll(poll.id), "Poll closed without a meeting.")} />}{poll.meeting_id && <Button variant="secondary" onClick={() => setSelected(poll.meeting_id ?? "")}>Open meeting record</Button>}</article>)}</div>}
      {(polls.data?.pages ?? 1) > 1 && <nav className="form-actions" aria-label="Poll pages"><Button variant="secondary" disabled={pollPage <= 1 || polls.isFetching || busy} onClick={() => setPollPage((page) => page - 1)}>Previous polls</Button><span>Page {polls.data?.page} of {polls.data?.pages}</span><Button variant="secondary" disabled={pollPage >= (polls.data?.pages ?? 1) || polls.isFetching || busy} onClick={() => setPollPage((page) => page + 1)}>Next polls</Button></nav>}
    </Panel>
    <Panel><h2>Meeting outcomes and attendance</h2><p>RSVP expresses intention to attend. The attendance below is a manager's recorded observation, with reasons and a correction history.</p>
      {meetings.isLoading ? <Loading label="Loading meeting records…" /> : meetings.error ? <ErrorState error={meetings.error} retry={() => void meetings.refetch()} /> : !meetings.data?.meetings.length ? <EmptyState title="No meetings">Schedule a meeting on the Meetings page or close a time poll.</EmptyState> : <Field label="Meeting"><select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Choose a meeting</option>{selected && record && !meetings.data.meetings.some((item) => item.id === selected) && <option value={selected}>{record.title} · selected meeting</option>}{meetings.data.meetings.map((item) => <option key={item.id} value={item.id}>{item.title} · {formatDate(item.starts_at)} · {item.lifecycle_state}</option>)}</select></Field>}
      {selectedMeeting.error && <ErrorState error={selectedMeeting.error} retry={() => void selectedMeeting.refetch()} />}
      {selectedMeeting.isLoading && selected && <Loading label="Loading selected meeting…" />}
      {record && !selectedMeeting.error && <MeetingEditor key={`${record.id}-${record.version}`} record={record} members={members} historyMembers={meetings.data?.members ?? members.map((member) => ({ ...member, active: true }))} timeZone={me.data?.profile.time_zone ?? "UTC"} currentUser={me.data?.user.id ?? ""} projectId={projectId} busy={busy} execute={doAction} />}
      {(meetings.data?.pages ?? 1) > 1 && <nav className="form-actions" aria-label="Meeting pages"><Button variant="secondary" disabled={meetingPage <= 1 || meetings.isFetching || busy} onClick={() => setMeetingPage((page) => page - 1)}>Previous meetings</Button><span>Page {meetings.data?.page} of {meetings.data?.pages}</span><Button variant="secondary" disabled={meetingPage >= (meetings.data?.pages ?? 1) || meetings.isFetching || busy} onClick={() => setMeetingPage((page) => page + 1)}>Next meetings</Button></nav>}
    </Panel>
  </div>;
}

function MeetingEditor({ record, members, historyMembers, timeZone, currentUser, projectId, busy, execute }: { record: MeetingRecord; members: { id: string; display_name: string }[]; historyMembers: { id: string; display_name: string; active: boolean }[]; timeZone: string; currentUser: string; projectId: string; busy: boolean; execute: (action: () => Promise<unknown>, message: string) => void }) {
  const [participants, setParticipants] = useState<Participant[]>(record.participants);
  const [expectedVersion, setExpectedVersion] = useState(record.version);
  const terminal = record.lifecycle_state === "cancelled" || record.lifecycle_state === "archived";
  const saveMinutes = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget, data = new FormData(form);
    execute(async () => { const result = await coordinationApi.saveRecord(record.id, { minutes: String(data.get("minutes")), decisions: String(data.get("decisions")), expected_version: expectedVersion }); setExpectedVersion(result.version); form.reset(); return result; }, "Meeting minutes saved. Existing confirmations refer to earlier versions until reconfirmed.");
  };
  return <div className="coord-meeting-editor"><h3>{record.title}</h3><p>{formatDate(record.starts_at)} – {formatDate(record.ends_at)} · {record.lifecycle_state}</p>
    <details className="coord-editor"><summary>Required and optional participants</summary><p>{record.participants.length ? record.participants.map((entry) => `${historyMembers.find((member) => member.id === entry.user_id)?.display_name ?? "Former member"} (${entry.required ? "required" : "optional"})`).join(" · ") : "No participant list has been saved. The meeting remains visible to the project team."}</p>{record.can_manage && !terminal && <><ParticipantPicker members={members} selected={participants.filter((entry) => members.some((member) => member.id === entry.user_id))} onChange={setParticipants} disabled={busy} /><Button disabled={busy || !participants.length} onClick={() => execute(async () => { const result = await coordinationApi.saveRecord(record.id, { participants, expected_version: expectedVersion }); setExpectedVersion(result.version); return result; }, "Meeting participants saved.")}>Save participants / initialise record</Button></>}</details>
    {record.can_manage && record.lifecycle_state === "scheduled" && <details className="coord-editor"><summary>Create a recurring series</summary><p>Creates separate real meetings at the same local time in {timeZone}; each occurrence can be edited or cancelled on the Meetings page.</p><form className="form-grid" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); execute(() => coordinationApi.repeat(record.id, Number(data.get("count")), Number(data.get("interval")), timeZone), "Recurring meeting occurrences created."); }}><Field label="Additional occurrences"><input type="number" name="count" min={1} max={12} defaultValue={3} required /></Field><Field label="Repeat"><select name="interval"><option value={7}>Every week</option><option value={14}>Every two weeks</option></select></Field><Button disabled={busy}>Create series</Button></form></details>}
    <h4>Minutes and decisions · version {record.version}</h4>{record.can_manage && record.can_record ? <DraftForm scope={`minutes:${projectId}:${record.id}`} fields={["minutes", "decisions"]} className="form-stack" onSubmit={saveMinutes}><Field label="Minutes"><textarea name="minutes" rows={6} maxLength={12000} defaultValue={record.minutes} /></Field><Field label="Decisions"><textarea name="decisions" rows={4} maxLength={6000} defaultValue={record.decisions} /></Field><Button disabled={busy}>Save minutes and decisions</Button></DraftForm> : <><p className="coord-prewrap">{record.minutes || "No minutes recorded."}</p><p className="coord-prewrap">{record.decisions || "No decisions recorded."}</p>{!record.can_record && !terminal && <p>Minutes and attendance can be recorded once the meeting starts.</p>}</>}
    {(record.minutes || record.decisions) && <><p>Current confirmations: {record.confirmations.filter((row) => row.current).map((row) => row.user.display_name).join(", ") || "None yet"}.</p><p className="muted">Earlier confirmations: {record.confirmations.filter((row) => !row.current).map((row) => `${row.user.display_name} (version ${row.version})`).join(", ") || "None"}.</p>{record.can_record && !record.confirmations.some((row) => row.user.id === currentUser && row.current) && <Button disabled={busy} variant="secondary" onClick={() => execute(() => coordinationApi.confirmMinutes(record.id, record.version), "You confirmed the current minutes and decisions.")}>Confirm I have read version {record.version}</Button>}</>}
    <h4>Actual attendance</h4><ul>{record.attendance.map((row) => <li key={row.user.id}><strong>{row.user.display_name}: {row.attended ? "Attended" : "Did not attend"}</strong> — {row.note} <small>Recorded by {row.recorded_by.display_name} · {formatDate(row.updated_at)}</small></li>)}</ul>
    {record.can_manage && record.can_record && <>{!record.record_id ? <p>Save minutes or participants first to initialise this meeting record.</p> : <form className="form-grid" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); execute(() => coordinationApi.attendance(record.id, String(data.get("user")), data.get("attended") === "yes", String(data.get("note"))), "Attendance saved with a retained correction history."); }}><Field label="Member"><select name="user" required>{historyMembers.map((member) => <option value={member.id} key={member.id}>{member.display_name}{member.active ? "" : " (former member)"}</option>)}</select></Field><Field label="Observation"><select name="attended"><option value="yes">Attended</option><option value="no">Did not attend</option></select></Field><Field label="Source / correction reason"><input name="note" required maxLength={500} /></Field><Button disabled={busy}>Record or correct attendance</Button></form>}</>}
    <h4>Action items</h4><ul>{record.actions.map((action) => <li key={action.task_id}><Link to={`/app/projects/${projectId}/tasks/${action.task_id}/`}>{action.title}</Link> · {action.status}{action.due_at && ` · ${formatDate(action.due_at)}`}</li>)}</ul>
    {record.can_manage && record.can_record && record.record_id && <form className="form-stack" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); execute(async () => { await coordinationApi.action(record.id, { title: String(data.get("title")), description: String(data.get("description")), due_at: instant(data.get("due")), assignee_ids: data.getAll("assignee").map(String) }); form.reset(); }, "Action item created as a real assigned task."); }}><Field label="Action title"><input name="title" minLength={3} maxLength={120} required /></Field><Field label="Action details"><textarea name="description" rows={3} maxLength={4000} /></Field><Field label="Due (your device time zone, optional)"><input type="datetime-local" name="due" /></Field><fieldset className="coord-participants"><legend>Assign current members</legend>{members.map((member) => <label key={member.id}><input type="checkbox" name="assignee" value={member.id} /> {member.display_name}</label>)}</fieldset><Button disabled={busy}>Create task from action</Button></form>}
    <details className="coord-editor"><summary>Record and correction history</summary><ul>{record.history.map((item) => <li key={item.id}><strong>{item.kind.replaceAll("_", " ")}</strong> · {item.actor.display_name} · {formatDate(item.created_at)}{typeof item.metadata.note === "string" && <p>{item.metadata.note}</p>}{typeof item.metadata.version === "number" && <p>Version {item.metadata.version}</p>}{typeof item.metadata.minutes === "string" && <p className="coord-prewrap">{item.metadata.minutes}</p>}{typeof item.metadata.decisions === "string" && <p className="coord-prewrap">{item.metadata.decisions}</p>}</li>)}</ul></details>
  </div>;
}
