import DraftForm from "../components/DraftForm";
import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { coordinationApi, type ContributionClaim } from "../api/coordination";
import { accountApi, membershipApi, projectApi, taskApi } from "../api/resources";
import { errorMessage } from "../api/client";
import { formatDate } from "../app/format";
import { Button, ConfirmAction, EmptyState, ErrorState, Field, Loading, Panel } from "../components/UI";
import "../coordination.css";

const statusLabels = { withdrawn: "Withdrawn", superseded: "Superseded by a revision", awaiting_collaborators: "Awaiting collaborator attribution", team_confirmed: "Team confirmed", changes_requested: "Changes requested", self_reported: "Self reported" };

export default function EvidencePage() {
  const { projectId = "" } = useParams();
  const client = useQueryClient();
  const today = new Date().toISOString().slice(0, 10);
  const [range, setRange] = useState({ start: today.slice(0, 8) + "01", end: today });
  const [revision, setRevision] = useState<ContributionClaim | null>(null);
  const [page, setPage] = useState(1);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const evidence = useQuery({ queryKey: ["coord-evidence", projectId, range.start, range.end, page], queryFn: () => coordinationApi.evidence(projectId, range.start, range.end, page), enabled: Boolean(projectId) });
  const me = useQuery({ queryKey: ["me"], queryFn: accountApi.me });
  const project = useQuery({ queryKey: ["project", projectId], queryFn: () => projectApi.get(projectId), enabled: Boolean(projectId) });
  const members = useQuery({ queryKey: ["memberships", projectId], queryFn: () => membershipApi.list(projectId), enabled: Boolean(projectId) });
  const tasks = useQuery({ queryKey: ["evidence-tasks", projectId], queryFn: () => taskApi.list(projectId, { scope: "all" }), enabled: Boolean(projectId) });
  const operation = useMutation({ mutationFn: (action: () => Promise<unknown>) => action(), onSuccess: async () => { setError(""); await client.invalidateQueries({ queryKey: ["coord-evidence", projectId] }); }, onError: (value) => { setNotice(""); setError(errorMessage(value)); } });
  const busy = operation.isPending;
  const archived = Boolean(project.data?.archived_at);
  const doAction = (action: () => Promise<unknown>, message: string) => operation.mutate(async () => { const result = await action(); setNotice(message); return result; });
  const createClaim = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form);
    doAction(async () => { await coordinationApi.claim({ project: projectId, title: String(data.get("title")), statement: String(data.get("statement")), artifact_url: String(data.get("link")), task_id: String(data.get("task")) || null, contributor_ids: data.getAll("contributor").map(String), supersedes_id: revision?.id ?? null }); form.reset(); setRevision(null); }, revision ? "Revised statement saved. Earlier statements and reviews remain in the history." : "Contribution statement submitted as self-reported evidence.");
  };
  if (project.isLoading || me.isLoading || evidence.isLoading) return <Loading label="Loading contribution evidence…" />;
  if (project.error || me.error || evidence.error) return <ErrorState error={project.error ?? me.error ?? evidence.error} retry={() => { void project.refetch(); void me.refetch(); void evidence.refetch(); }} />;
  return <div className="page-stack coordination-page"><header className="page-heading"><div><p className="eyebrow">{project.data?.name}</p><h1>Contribution evidence</h1><p>Keep recorded actions, personal statements and independent team confirmation visible as separate sources.</p></div><Link className="button button--secondary" to={`/app/projects/${projectId}/contributions/`}>Activity charts & exports</Link></header>
    {error && <p className="form-error" role="alert">{error}</p>}{notice && <p className="success-message" role="status">{notice}</p>}{archived && <p role="status">This project is archived. Contribution statements and reviews are read-only.</p>}
    <Panel><h2>System records · current and former members</h2><form className="filter-bar" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setPage(1); setRange({ start: String(data.get("start")), end: String(data.get("end")) }); }}><Field label="Records from"><input type="date" name="start" defaultValue={range.start} required /></Field><Field label="Through"><input type="date" name="end" defaultValue={range.end} required /></Field><Button variant="secondary">Apply date range</Button></form><p className="muted">{evidence.data?.basis}</p><p>System record range: {evidence.data?.range_start} to {evidence.data?.range_end}. Statements below retain their complete version and review history.</p>
      <div className="coord-table-scroll"><table className="coord-evidence-table"><caption>Recorded facts are counts, not a contribution score or grade.</caption><thead><tr><th scope="col">Member</th><th scope="col">System actions</th><th scope="col">Distinct tasks marked done</th><th scope="col">Comments created</th><th scope="col">Accepted RSVPs</th><th scope="col">Recorded actual attendance</th></tr></thead><tbody>{evidence.data?.members.map((member) => <tr key={member.id}><th scope="row">{member.display_name}<small>{member.active ? "Current member" : "Former member"} · {member.role}</small></th><td>{member.system_events}</td><td>{member.tasks_marked_done}</td><td>{member.comments_created}</td><td>{member.accepted_rsvps}</td><td>{member.recorded_attendance}</td></tr>)}</tbody></table></div>
    </Panel>
    {!archived && <Panel><h2>{revision ? `Revise: ${revision.title}` : "Explain your contribution"}</h2><p>Describe the work you performed and link to a result. Joint contributors confirm their own attribution; an independent owner or facilitator can review the statement. Neither a statement nor a confirmation is an automatic grade.</p>{(members.error || tasks.error) && <ErrorState error={members.error ?? tasks.error} retry={() => { void members.refetch(); void tasks.refetch(); }} />}<DraftForm scope={`claim:${projectId}:${revision?.id ?? "new"}`} fields={["title", "statement"]} key={revision?.id ?? "new"} className="form-stack" onSubmit={createClaim}><Field label="Contribution title"><input name="title" minLength={3} maxLength={160} required defaultValue={revision?.title ?? ""} /></Field><Field label="What I contributed"><textarea name="statement" minLength={10} maxLength={6000} rows={6} required defaultValue={revision?.statement ?? ""} /></Field><Field label="Result / evidence URL (optional)" hint="Use an HTTP(S) link you are permitted to share. StudyCrew does not fetch or verify this link."><input name="link" type="url" maxLength={2048} defaultValue={revision?.artifact_url ?? ""} /></Field><Field label="Related task (optional)"><select name="task" defaultValue={revision?.task_id ?? ""}><option value="">No task link</option>{tasks.data?.results.map((task) => <option value={task.id} key={task.id}>{task.title}{task.archived_at ? " (archived)" : ""}</option>)}</select></Field><fieldset className="coord-participants"><legend>Joint contributors (optional)</legend>{members.data?.results.filter((member) => member.user.id !== me.data?.user.id).map((member) => <label key={member.user.id}><input name="contributor" type="checkbox" value={member.user.id} defaultChecked={revision?.contributors.some((entry) => entry.user.id === member.user.id)} /> {member.user.display_name}</label>)}</fieldset><div className="form-actions"><Button disabled={busy || members.isLoading || tasks.isLoading || Boolean(members.error || tasks.error)}>{revision ? "Submit revised statement" : "Submit contribution statement"}</Button>{revision && <Button variant="quiet" type="button" disabled={busy} onClick={() => setRevision(null)}>Cancel revision</Button>}</div></DraftForm></Panel>}
    <Panel><h2>Statements and team review</h2>{!evidence.data?.claims.length ? <EmptyState title="No contribution statements">Members can describe outcomes that system activity counts do not capture.</EmptyState> : <div className="coord-list">{evidence.data.claims.map((claim) => <article className="coord-card" key={claim.id}><div className="section-heading"><h3>{claim.title}</h3><span className={`coord-evidence-state coord-evidence-state--${claim.status}`}>{statusLabels[claim.status]}</span></div><p>Statement by {claim.author.display_name} · {formatDate(claim.created_at)}{claim.supersedes_id ? " · revised statement" : ""}</p><p className="coord-prewrap">{claim.statement}</p>{claim.artifact_url && <p><a href={claim.artifact_url} target="_blank" rel="noopener noreferrer">Open submitted evidence</a> <span className="muted">Member-supplied link</span></p>}{claim.task_id && <p><Link to={`/app/projects/${projectId}/tasks/${claim.task_id}/`}>Related task: {claim.task_title}</Link></p>}<p>Joint attribution: {claim.contributors.length ? claim.contributors.map((row) => `${row.user.display_name} (${row.response})`).join(" · ") : "No collaborators named"}.</p>
      {claim.can_respond && <div className="form-actions"><Button disabled={busy} variant="secondary" onClick={() => doAction(() => coordinationApi.respondClaim(claim.id, "confirmed"), "You confirmed your joint contribution attribution.")}>Confirm my attribution</Button><Button disabled={busy} variant="quiet" onClick={() => doAction(() => coordinationApi.respondClaim(claim.id, "declined"), "Your attribution was declined; the author can submit a corrected statement.")}>Decline my attribution</Button></div>}
      {claim.can_review && <form className="form-grid" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); doAction(() => coordinationApi.reviewClaim(claim.id, data.get("outcome") === "confirmed" ? "confirmed" : "changes_requested", String(data.get("note"))), "Independent team review recorded."); }}><Field label="Review outcome"><select name="outcome"><option value="changes_requested">Request changes</option><option value="confirmed">Confirm evidence for the team</option></select></Field><Field label="Review note"><input name="note" minLength={1} maxLength={1000} required /></Field><Button disabled={busy}>Save review</Button></form>}
      <div className="form-actions">{claim.can_revise && <Button disabled={busy} variant="secondary" onClick={() => { setRevision(claim); window.scrollTo({ top: 0, behavior: "smooth" }); }}>Create revised statement</Button>}{claim.can_withdraw && <ConfirmAction busy={busy} triggerLabel="Withdraw statement" confirmLabel="Withdraw" message="Withdraw this statement from active evidence? Its content and review history will remain available to the authorised team." onConfirm={() => doAction(() => coordinationApi.withdrawClaim(claim.id), "Statement withdrawn; its history is retained.")} />}</div>
      <details className="coord-editor"><summary>Independent review history ({claim.reviews.length})</summary>{claim.reviews.length ? <ul>{claim.reviews.map((review, index) => <li key={`${review.created_at}-${index}`}><strong>{review.outcome.replaceAll("_", " ")}</strong> by {review.reviewer.display_name} · {formatDate(review.created_at)}<p>{review.note}</p></li>)}</ul> : <p>No independent review has been recorded.</p>}</details></article>)}</div>}{(evidence.data?.pages ?? 1) > 1 && <nav className="form-actions" aria-label="Statement pages"><Button variant="secondary" disabled={page <= 1 || busy || evidence.isFetching} onClick={() => setPage((value) => value - 1)}>Previous statements</Button><span>Page {evidence.data?.page} of {evidence.data?.pages}</span><Button variant="secondary" disabled={page >= (evidence.data?.pages ?? 1) || busy || evidence.isFetching} onClick={() => setPage((value) => value + 1)}>Next statements</Button></nav>}</Panel>
  </div>;
}
