import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { operationsApi } from "../api/operations";
import { discussionsApi } from "../api/discussions";
import { accountApi } from "../api/resources";
import ListPagination from "../components/ListPagination";
import { Button, ErrorState, Field, Loading, Panel, StatusBadge } from "../components/UI";
import { TicketCard } from "./SupportPage";

export default function OperationsPage() {
  const [ticketPage, setTicketPage] = useState(1), [contactPage, setContactPage] = useState(1), [mailPage, setMailPage] = useState(1);
  const [reportPage, setReportPage] = useState(1);
  const cache = useQueryClient();
  const me = useQuery({ queryKey: ["me"], queryFn: accountApi.me });
  const allowed = me.data?.permissions.site_moderator ?? false;
  const reports = useQuery({ queryKey: ["post-reports", reportPage], queryFn: () => discussionsApi.reports(reportPage), enabled: allowed });
  const moderate = useMutation({ mutationFn: ({ id, hide, reason }: { id: string; hide: boolean; reason: string }) => discussionsApi.moderate(id, hide, reason), onSuccess: () => { void cache.invalidateQueries({ queryKey: ["post-reports"] }); void cache.invalidateQueries({ queryKey: ["admin-support"] }); void cache.invalidateQueries({ queryKey: ["project-posts"] }); } });
  const summary = useQuery({ queryKey: ["operations-summary"], queryFn: operationsApi.summary, enabled: allowed, refetchInterval: 30000 });
  const tickets = useQuery({ queryKey: ["admin-support", ticketPage], queryFn: () => operationsApi.adminTickets(ticketPage), enabled: allowed });
  const contacts = useQuery({ queryKey: ["admin-contacts", contactPage], queryFn: () => operationsApi.adminContacts(contactPage), enabled: allowed });
  const respond = useMutation({ mutationFn: ({ id, response }: { id: string; response: string }) => operationsApi.respondContact(id, response), onSuccess: () => { void cache.invalidateQueries({ queryKey: ["admin-contacts"] }); void cache.invalidateQueries({ queryKey: ["admin-deliveries"] }); } });
  const mail = useQuery({ queryKey: ["admin-deliveries", mailPage], queryFn: () => operationsApi.adminDeliveries(mailPage), enabled: allowed, refetchInterval: 30000 });
  const notices = useQuery({ queryKey: ["service-notices"], queryFn: operationsApi.notices, enabled: allowed });
  const createNotice = useMutation({ mutationFn: operationsApi.createNotice, onSuccess: () => { void cache.invalidateQueries({ queryKey: ["service-notices"] }); } });
  const end = useMutation({ mutationFn: operationsApi.endNotice, onSuccess: () => { void cache.invalidateQueries({ queryKey: ["service-notices"] }); } });
  const retry = useMutation({ mutationFn: ({ id, reason, acknowledge }: { id: string; reason: string; acknowledge: boolean }) => operationsApi.retryDelivery(id, reason, acknowledge), onSuccess: () => { void cache.invalidateQueries({ queryKey: ["admin-deliveries"] }); } });
  if (me.isLoading) return <Loading />;
  if (me.error) return <ErrorState error={me.error} retry={() => void me.refetch()} />;
  if (!allowed) return <Panel><h2>Operations</h2><p>Site moderator permission is required.</p></Panel>;
  return <div className="page-stack"><div className="page-heading"><div><h2>Service operations</h2><p>Support, notices and delivery health.</p></div><a href="/control/" className="button button--quiet">Moderation centre</a></div>
    <Panel><h3>Health and usage</h3>{summary.isLoading && <Loading size="compact" label="Loading service health…" />}{summary.error && <ErrorState error={summary.error} size="compact" retry={() => void summary.refetch()} />}{summary.data && <><div className="launch-stats"><div><strong>{summary.data.weekly_active_teams}</strong><span>Active teams this week</span></div><div><strong>{summary.data.open_support}</strong><span>Open support cases</span></div><div><strong>{summary.data.mail.queued ?? 0}</strong><span>Queued emails</span></div><div><strong>{summary.data.mail.failed ?? 0}</strong><span>Failed emails</span></div></div><p>Daily mail safety limit: {summary.data.mail_budget.daily_limit}. Oldest queued: {summary.data.oldest_queued_at ? new Date(summary.data.oldest_queued_at).toLocaleString() : "none"}.</p>{summary.data.backup && <p role={summary.data.backup.healthy ? "status" : "alert"}>Verified backup: {summary.data.backup.healthy ? "current" : "missing or overdue"}. Last success: {summary.data.backup.last_verified_at ? new Date(summary.data.backup.last_verified_at).toLocaleString() : "none"}; allowed age {summary.data.backup.max_age_hours} hours.</p>}{summary.data.workers.map(worker => <p key={worker.name}>{worker.name}: last reported {new Date(worker.last_run_at).toLocaleString()}</p>)}<p className="muted">Activity counts show product usage, not student performance. Request totals below cover mutations and errors; full request timing is in service logs.</p><div className="table-scroll"><table><thead><tr><th>Date</th><th>Area</th><th>Requests</th><th>Errors</th><th>Average ms</th></tr></thead><tbody>{summary.data.requests.map(row => <tr key={row.id}><td>{row.day}</td><td>{row.route_group}</td><td>{row.requests}</td><td>{row.errors}</td><td>{row.requests ? Math.round(row.total_ms / row.requests) : 0}</td></tr>)}</tbody></table></div></>}</Panel>
    <Panel><h3>Service notices</h3><form className="launch-form" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); createNotice.mutate({ title: String(data.get("title")), body: String(data.get("body")), severity: String(data.get("severity")), starts_at: new Date().toISOString(), ends_at: data.get("ends_at") ? new Date(String(data.get("ends_at"))).toISOString() : null }, { onSuccess: () => form.reset() }); }}><Field label="Title"><input name="title" required maxLength={160} /></Field><Field label="Message"><textarea name="body" required maxLength={2000} /></Field><div className="launch-grid"><Field label="Type"><select name="severity"><option value="information">Information</option><option value="maintenance">Maintenance</option><option value="incident">Incident</option></select></Field><Field label="Ends at (optional)"><input name="ends_at" type="datetime-local" /></Field></div><Button disabled={createNotice.isPending}>Publish notice</Button>{createNotice.error && <ErrorState error={createNotice.error} />}</form>{notices.isLoading && <Loading size="compact" label="Loading service notices…" />}{notices.error && <ErrorState error={notices.error} size="compact" retry={() => void notices.refetch()} />}{!notices.isLoading && !notices.error && notices.data?.results.length === 0 && <p>No active service notices.</p>}{notices.data?.results.map(notice => <div className="compact-row" key={notice.id}><span><strong>{notice.title}</strong><small>{notice.body}</small></span><Button variant="quiet" disabled={end.isPending} onClick={() => end.mutate(notice.id)}>End notice</Button></div>)}{end.error && <ErrorState error={end.error} />}</Panel>
    <Panel><h3>Reported project content</h3><p>Review only the specific content reported by a team member. The reporter can follow the recorded decision in their support case.</p>{reports.isLoading && <Loading size="compact" label="Loading content reports…" />}{reports.error && <ErrorState error={reports.error} size="compact" retry={() => void reports.refetch()} />}{!reports.isLoading && !reports.error && reports.data?.results.length === 0 && <p>No reported project content.</p>}{reports.data?.results.map(row => <article className="launch-ticket" key={row.id}><h4>{row.title}</h4><p className="launch-preserve">{row.description}</p><StatusBadge value={row.status} />{row.status === "resolved" ? <p>{row.resolution}</p> : <form className="launch-form" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); moderate.mutate({ id: row.id, hide: data.has("hide"), reason: String(data.get("reason")) }); }}><Field label="Decision and reason"><textarea name="reason" minLength={5} maxLength={2000} required /></Field><label><input type="checkbox" name="hide" /> Hide this reported content from its project</label><Button disabled={moderate.isPending}>Resolve content report</Button></form>}</article>)}{moderate.error && <ErrorState error={moderate.error} />}<ListPagination info={reports.data} page={reportPage} onChange={setReportPage} label="Content reports" /></Panel>
    <Panel><h3>Support cases</h3>{tickets.isLoading && <Loading size="compact" label="Loading support cases…" />}{tickets.error && <ErrorState error={tickets.error} size="compact" retry={() => void tickets.refetch()} />}{!tickets.isLoading && !tickets.error && tickets.data?.results.length === 0 && <p>No support cases.</p>}{tickets.data?.results.map(ticket => <TicketCard key={ticket.id} ticket={ticket} admin />)}<ListPagination info={tickets.data} page={ticketPage} onChange={setTicketPage} label="Support cases" /></Panel>
    <Panel><h3>Confirmed public requests</h3><p>Requests from people who cannot sign in. Replies go only to the address they confirmed.</p>{contacts.isLoading && <Loading size="compact" label="Loading public requests…" />}{contacts.error && <ErrorState error={contacts.error} size="compact" retry={() => void contacts.refetch()} />}{!contacts.isLoading && !contacts.error && contacts.data?.results.length === 0 && <p>No confirmed requests.</p>}{contacts.data?.results.map(row => <article className="launch-ticket" key={row.id}><h4>{row.subject}</h4><p>{row.email} · {row.category}</p><p className="preserve-lines">{row.description}</p>{row.resolved_at && <p>Resolved {new Date(row.resolved_at).toLocaleString()}: {row.response}</p>}<form className="launch-form" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; respond.mutate({ id: row.id, response: String(new FormData(form).get("response")) }, { onSuccess: () => form.reset() }); }}><Field label="Response"><textarea name="response" maxLength={2000} required /></Field><Button disabled={respond.isPending}>Send response and resolve</Button></form></article>)}{respond.error && <ErrorState error={respond.error} />}{respond.isSuccess && <p role="status">Response queued for delivery.</p>}<ListPagination info={contacts.data} page={contactPage} onChange={setContactPage} label="Public requests" /></Panel>
    <Panel><h3>Recent delivery attempts</h3>{mail.isLoading && <Loading size="compact" label="Loading delivery attempts…" />}{mail.error && <ErrorState error={mail.error} size="compact" retry={() => void mail.refetch()} />}{!mail.isLoading && !mail.error && mail.data?.results.length === 0 && <p>No delivery attempts.</p>}{mail.data?.results.map(row => <article className="launch-ticket" key={row.id}><div className="launch-row"><strong>{row.subject}</strong><StatusBadge value={row.status} /></div><p>{row.failure_reason || `Attempts: ${row.attempts}`}</p>{row.status === "failed" && <form className="launch-form" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); retry.mutate({ id: row.id, reason: String(data.get("reason")), acknowledge: data.has("acknowledge") }); }}><Field label="Reason for retry"><input name="reason" minLength={5} maxLength={160} required /></Field><label><input type="checkbox" name="acknowledge" /> I checked the provider and understand an uncertain message may already have arrived.</label><Button variant="secondary" disabled={retry.isPending}>Retry delivery</Button></form>}</article>)}{retry.error && <ErrorState error={retry.error} />}<ListPagination info={mail.data} page={mailPage} onChange={setMailPage} label="Delivery attempts" /></Panel>
  </div>;
}
