import DraftForm from "../components/DraftForm";
import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate, useParams } from "react-router-dom";
import { campusApi, type AcademicTask, type ProjectPlan } from "../api/campus";
import { errorMessage } from "../api/client";
import { formatDate, toDateTimeLocal } from "../app/format";
import { Button, ConfirmAction, EmptyState, ErrorState, Field, Loading, Panel, StatusBadge } from "../components/UI";
import "../campus.css";

function instant(value: FormDataEntryValue | null) {
  if (!value) return null;
  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) throw new Error("Choose a valid date and time.");
  return date.toISOString();
}

type Change = { path: string; data?: unknown; method?: string; message?: string };

function TaskPlanning({ task, plan, readOnly, busy, run, submit }: {
  task: AcademicTask; plan: ProjectPlan; readOnly: boolean; busy: boolean;
  run: (change: Change) => void;
  submit: (event: FormEvent<HTMLFormElement>, path: string, build: (data: FormData) => unknown, method?: string) => void;
}) {
  const [newChecklist, setNewChecklist] = useState("");
  const [open, setOpen] = useState(false);
  const prefix = `tasks/${task.id}/`;
  const otherTasks = plan.task_choices.filter((item) => item.id !== task.id);
  const taskReadOnly = readOnly || task.status === "done";
  return <details className="panel" onToggle={(event) => setOpen(event.currentTarget.open)}><summary><strong>{task.title}</strong> · {task.status.replaceAll("_", " ")}{task.parent && " · Subtask"}</summary>
    {open && <div className="page-stack">{!readOnly && <form className="inline-form" onSubmit={event => submit(event, `${prefix}copy/`, data => ({ title: data.get("title"), reuse_dependencies: data.has("reuse_dependencies") }))}><Field label="Copy as a new task"><input name="title" required minLength={3} maxLength={120} defaultValue={`${task.title.slice(0, 110)} (copy)`} /></Field><label><input name="reuse_dependencies" type="checkbox" /> Reuse current prerequisites</label><Button variant="secondary" disabled={busy}>Copy task structure</Button><p className="muted">Copies text, tags, estimate and checklist. Completion, dates, assignments, review and result links start empty.</p></form>}<p><Link to={`/app/projects/${task.project}/tasks/${task.id}/`}>Open task, change status and assign teammates</Link></p><p>Internal: {formatDate(task.internal_due_at)} · Official: {formatDate(task.official_due_at)} · Review: {task.review_state.replaceAll("_", " ")}</p>
      <form className="form-grid" onSubmit={(event) => submit(event, prefix, (data) => ({ tags: String(data.get("tags")).split(",").map(value => value.trim()).filter(Boolean), estimate_hours: data.get("estimate_hours") || null, acceptance: data.get("acceptance"), internal_due_at: instant(data.get("internal_due_at")), official_due_at: instant(data.get("official_due_at")), outcome_url: data.get("outcome_url"), parent: data.get("parent") || null, milestone: data.get("milestone") || null, reviewer: data.get("reviewer") || null, dependencies: data.getAll("dependencies") }), "PATCH")}>
        <fieldset className="form-grid" disabled={taskReadOnly || busy}><legend>Acceptance and relationships</legend>
          <Field label="Tags (up to ten, comma separated)"><input name="tags" defaultValue={(task.tags ?? []).join(", ")} maxLength={310} /></Field><Field label="Estimated work hours (self-reported)"><input name="estimate_hours" type="number" min={0} max={1000} step="0.25" defaultValue={task.estimate_hours ?? ""} /></Field><Field label="Acceptance criteria"><textarea name="acceptance" defaultValue={task.acceptance} maxLength={4000} rows={3} /></Field>
          <div className="card-grid"><Field label="Internal deadline"><input name="internal_due_at" type="datetime-local" defaultValue={toDateTimeLocal(task.internal_due_at)} /></Field><Field label="Official deadline"><input name="official_due_at" type="datetime-local" defaultValue={toDateTimeLocal(task.official_due_at)} /></Field></div>
          <Field label="Deliverable link"><input name="outcome_url" type="url" maxLength={2048} defaultValue={task.outcome_url} placeholder="https://..." /></Field>
          <div className="card-grid"><Field label="Parent task"><select name="parent" defaultValue={task.parent ?? ""}><option value="">Standalone task</option>{otherTasks.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></Field><Field label="Milestone"><select name="milestone" defaultValue={task.milestone ?? ""}><option value="">No milestone</option>{plan.milestones.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></Field><Field label="Reviewer"><select name="reviewer" defaultValue={task.reviewer ?? ""}><option value="">No review required</option>{plan.members.map((member) => <option key={member.id} value={member.id}>{member.display_name}</option>)}</select></Field></div>
          <fieldset className="check-list"><legend>Prerequisite tasks</legend>{otherTasks.map((item) => <label key={item.id}><input type="checkbox" name="dependencies" value={item.id} defaultChecked={task.dependencies.includes(item.id)} /> {item.title}</label>)}</fieldset>
          <Button disabled={busy}>Save task plan</Button>
        </fieldset>
      </form>
      <div><h4>Task checklist</h4>{task.checklist.map((item) => <label className="compact-row" key={item.id}><input type="checkbox" checked={item.checked} disabled={taskReadOnly || busy} onChange={(event) => run({ path: `${prefix}checklist/${item.id}/`, method: "PATCH", data: { checked: event.target.checked } })} /> {item.text}</label>)}{!taskReadOnly && <form className="inline-form" onSubmit={(event) => { event.preventDefault(); run({ path: `${prefix}checklist/`, data: { text: newChecklist } }); setNewChecklist(""); }}><Field label="New checklist item"><input required maxLength={300} value={newChecklist} onChange={(event) => setNewChecklist(event.target.value)} /></Field><Button disabled={busy}>Add checklist item</Button></form>}</div>
      {!taskReadOnly && <form className="inline-form" onSubmit={(event) => submit(event, "task-create/", (data) => ({ title: data.get("title"), parent: task.id }))}><Field label="New child task"><input name="title" required minLength={3} maxLength={120} /></Field><Button disabled={busy}>Create subtask</Button></form>}
      {task.review_note && <p>Review note: {task.review_note}</p>}
      {!taskReadOnly && task.reviewer && task.review_state !== "requested" && <Button variant="secondary" disabled={busy} onClick={() => run({ path: `${prefix}request-review/`, message: "Deliverable sent for review." })}>Request deliverable review</Button>}
      {!taskReadOnly && task.reviewer === plan.current_user && task.review_state === "requested" && <form className="form-grid" onSubmit={(event) => submit(event, `${prefix}review/`, (data) => ({ approved: data.get("decision") === "approved", note: data.get("note") }))}><Field label="Review decision"><select name="decision"><option value="approved">Approve deliverable</option><option value="changes">Request changes</option></select></Field><Field label="Review note"><textarea name="note" maxLength={1000} /></Field><Button disabled={busy}>Record review</Button></form>}
      {task.status === "done" && <p className="muted">Reopen this task before changing its plan or checklist.</p>}
    </div>}
  </details>;
}

export default function ProjectPlanPage() {
  const { projectId = "" } = useParams();
  const client = useQueryClient();
  const navigate = useNavigate();
  const [taskPage, setTaskPage] = useState(1);
  const plan = useQuery({ queryKey: ["project-plan", projectId, taskPage], queryFn: () => campusApi.plan(projectId, taskPage), enabled: Boolean(projectId) });
  const overview = useQuery({ queryKey: ["campus"], queryFn: campusApi.overview });
  const isOwner = plan.data?.project.role === "owner";
  const joins = useQuery({ queryKey: ["campus-joins", projectId], queryFn: () => campusApi.joins(projectId), enabled: Boolean(projectId && isOwner) });
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [shareLink, setShareLink] = useState("");
  const [handover, setHandover] = useState("");
  const [nextOwner, setNextOwner] = useState("");
  const change = useMutation({
    mutationFn: ({ path, data = {}, method = "POST" }: Change) => campusApi.projectAction<{ join_url?: string }>(projectId, path, data, method),
    onSuccess: async (result, variables) => {
      setError(""); setMessage(variables.message ?? "Saved."); if (result?.join_url) setShareLink(result.join_url);
      await Promise.all([client.invalidateQueries({ queryKey: ["project-plan", projectId] }), client.invalidateQueries({ queryKey: ["campus"] }), client.invalidateQueries({ queryKey: ["campus-joins", projectId] }), client.invalidateQueries({ queryKey: ["tasks", projectId] }), client.invalidateQueries({ queryKey: ["campus-todos"] }), client.invalidateQueries({ queryKey: ["projects"] }), client.invalidateQueries({ queryKey: ["memberships", projectId] })]);
      if (variables.path === "leave/") navigate("/app/campus/");
    }, onError: (e) => setError(errorMessage(e)),
  });
  const run = (action: Change) => { setError(""); setMessage(""); change.mutate(action); };
  const submit = (event: FormEvent<HTMLFormElement>, path: string, build: (data: FormData) => unknown, method = "POST") => {
    event.preventDefault(); try { const form = event.currentTarget; change.mutate({ path, data: build(new FormData(form)), method }, { onSuccess: () => form.reset() }); } catch (e) { setError(errorMessage(e)); }
  };
  if (plan.isLoading || overview.isLoading) return <Loading label="Loading the assignment plan…" />;
  if (plan.error || overview.error) return <ErrorState error={plan.error ?? overview.error} retry={() => { void plan.refetch(); void overview.refetch(); }} />;
  if (!plan.data) return null;
  const data = plan.data;
  const readOnly = Boolean(data.project.archived_at);
  const manager = ["owner", "facilitator"].includes(data.project.role);
  const busy = change.isPending;
  const agreement = data.agreement;
  const submission = data.submission;
  const others = data.members.filter((member) => member.id !== data.current_user);
  const confirmationNames = (confirmations: { user: string; revision: number }[], revision: number) => data.members.filter((member) => confirmations.some((c) => c.user === member.id && c.revision === revision)).map((m) => m.display_name).join(", ") || "No confirmations yet";
  return <div className="page-stack campus-page"><div className="page-heading"><div><p className="eyebrow">Coursework</p><h2>Assignment plan</h2><p>Agree deliverables, dependencies, reviews and a shared submission checklist.</p></div><Link className="button button--quiet" to={`/app/projects/${projectId}/resources/`}>Resource links</Link></div>
    {error && <p className="notice notice--error" role="alert">{error}</p>}{message && <p className="notice" role="status">{message}</p>}{readOnly && <p className="notice">This project is archived. Its plan is read-only.</p>}
    <Panel><h3>Courses and term</h3>{data.course_links.map((link) => <div className="compact-row" key={link.id}><span>{link.course.university} · {link.course.code} · {link.term.year} {link.term.name}</span>{manager && !readOnly && <Button variant="quiet" disabled={busy} onClick={() => run({ path: `course-links/${link.id}/`, method: "DELETE" })}>Remove association</Button>}</div>)}{manager && !readOnly && <form className="inline-form" onSubmit={(event) => submit(event, "course-links/", (form) => ({ course: form.get("course"), term: form.get("term") }))}><Field label="My course"><select name="course" required defaultValue=""><option value="" disabled>Choose a course</option>{overview.data?.courses.map((course) => <option key={course.id} value={course.id}>{course.university} · {course.code}</option>)}</select></Field><Field label="My term"><select name="term" required defaultValue=""><option value="" disabled>Choose a term</option>{overview.data?.terms.filter((term) => !term.archived_at).map((term) => <option key={term.id} value={term.id}>{term.university} · {term.year} {term.name}</option>)}</select></Field><Button disabled={busy}>Associate course</Button></form>}<Link to="/app/campus/">Manage my courses and terms</Link></Panel>
    {manager && !readOnly && <Panel><h3>Start from an assignment template</h3><p>Each template creates five editable tasks, prerequisites, checklists and submission checks in this project.</p><div className="row-actions">{overview.data?.templates.map((template) => <ConfirmAction key={template.key} triggerLabel={template.name} triggerVariant="secondary" confirmLabel="Create template tasks" message={`Add ${template.task_count} new ${template.name.toLowerCase()} tasks and their checklists to this workspace?`} busy={busy} onConfirm={() => run({ path: "template/", data: { template: template.key }, message: "Assignment tasks and checklists created." })} />)}</div></Panel>}
    <Panel><h3>Milestones</h3>{data.milestones.map((milestone) => <div className="compact-row" key={milestone.id}><span><strong>{milestone.title}</strong><small>{formatDate(milestone.due_at)}</small></span><label><input type="checkbox" checked={milestone.done} disabled={!manager || readOnly || busy} onChange={(event) => run({ path: `milestones/${milestone.id}/`, method: "PATCH", data: { done: event.target.checked } })} /> Complete</label></div>)}{manager && !readOnly && <form className="inline-form" onSubmit={(event) => submit(event, "milestones/", (form) => ({ title: form.get("title"), due_at: instant(form.get("due_at")) }))}><Field label="Milestone title"><input name="title" required maxLength={120} /></Field><Field label="Due date"><input name="due_at" type="datetime-local" /></Field><Button disabled={busy}>Add milestone</Button></form>}</Panel>
    <section aria-labelledby="academic-tasks-heading"><h3 id="academic-tasks-heading">Tasks, subtasks and reviews</h3><p>All prerequisites, child tasks and checklist items must be complete before a task can be marked done. A nominated reviewer must also approve its deliverable.</p>{data.tasks.length ? <div className="page-stack">{data.tasks.map((task) => <TaskPlanning key={task.id} task={task} plan={data} readOnly={readOnly} busy={busy} run={run} submit={submit} />)}</div> : <EmptyState title="No current tasks">Apply a template or create a task in the Tasks tab.</EmptyState>}</section>
    <div className="row-actions"><Button variant="quiet" disabled={data.task_pagination.page <= 1 || plan.isFetching} onClick={() => setTaskPage(data.task_pagination.page - 1)}>Previous task plans</Button><span>{data.task_pagination.total} tasks · Page {data.task_pagination.page} of {data.task_pagination.pages}</span><Button variant="quiet" disabled={data.task_pagination.page >= data.task_pagination.pages || plan.isFetching} onClick={() => setTaskPage(data.task_pagination.page + 1)}>Next task plans</Button></div>
    {data.risks && <Panel><h3>Work needing attention</h3><p>{data.risks.unassigned} open tasks without an assignee · {data.risks.overdue} overdue · {data.risks.blocked} blocked · {data.risks.open_dependencies} unfinished prerequisite links</p>{data.risks.blocked_tasks.map(task => <p key={task.id}><Link to={`/app/projects/${projectId}/tasks/${task.id}/`}>{task.title}</Link> · Blocked since {formatDate(task.since)}</p>)}<p className="muted">These are current recorded states and self-reported estimates. They do not predict quality or a grade.</p></Panel>}
    {!readOnly && <Panel><h3>Update several tasks</h3><form className="launch-form" onSubmit={event => submit(event, "tasks/bulk/", form => ({ task_ids: form.getAll("task_ids"), ...(form.get("priority") ? { priority: form.get("priority") } : {}), ...(form.has("change_assignees") ? { assignees: form.getAll("assignees") } : {}), ...(form.has("change_due") ? { internal_due_at: instant(form.get("due")) } : {}) }))}><Field label="Current tasks (choose at most 50)"><select name="task_ids" multiple required>{data.task_choices.filter(task => task.status !== "done").map(task => <option key={task.id} value={task.id}>{task.title}</option>)}</select></Field><Field label="Priority"><select name="priority"><option value="">Keep current priority</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></Field><label><input name="change_assignees" type="checkbox" /> Replace assignees for selected tasks (an empty selection clears them)</label><Field label="New assignees"><select name="assignees" multiple>{data.members.map(member => <option key={member.id} value={member.id}>{member.display_name}</option>)}</select></Field><label><input name="change_due" type="checkbox" /> Change internal deadline (blank clears it)</label><Field label="New internal deadline"><input name="due" type="datetime-local" /></Field><Button disabled={busy}>Apply changes to selected tasks</Button><p className="muted">All selected tasks must pass validation. A failure leaves the whole batch unchanged.</p></form></Panel>}
    <Panel><h3>Team agreement</h3>{agreement && <><p style={{ whiteSpace: "pre-wrap" }}>{agreement.body}</p><p className="muted">Revision {agreement.revision} · Confirmed by: {confirmationNames(agreement.confirmations, agreement.revision)}</p>{!readOnly && <Button variant="secondary" disabled={busy || agreement.confirmations.some((c) => c.user === data.current_user && c.revision === agreement.revision)} onClick={() => run({ path: "agreement/confirm/", data: { revision: agreement.revision } })}>Confirm this agreement</Button>}</>}{manager && !readOnly && <DraftForm scope={`agreement:${projectId}`} fields={["body"]} className="form-grid" onSubmit={(event) => submit(event, "agreement/", (form) => ({ body: form.get("body"), expected_revision: agreement?.revision ?? 0 }), "PUT")}><Field label="Roles, communication, meeting expectations and how to resolve blockers"><textarea key={agreement?.revision ?? 0} name="body" defaultValue={agreement?.body ?? ""} required maxLength={6000} rows={5} /></Field><Button disabled={busy}>Save a new agreement revision</Button></DraftForm>}<p className="muted">An edited agreement requires each member to confirm the latest revision again.</p></Panel>
    <Panel><h3>Submission checklist and receipt</h3>{manager && !readOnly && !submission?.submitted_at && <form className="inline-form" onSubmit={(event) => submit(event, "submission/", (form) => ({ official_due_at: instant(form.get("official_due_at")), internal_due_at: instant(form.get("internal_due_at")) }), "PATCH")}><Field label="Internal team deadline"><input name="internal_due_at" type="datetime-local" defaultValue={toDateTimeLocal(submission?.internal_due_at ?? null)} /></Field><Field label="Official deadline"><input name="official_due_at" type="datetime-local" defaultValue={toDateTimeLocal(submission?.official_due_at ?? null)} /></Field><Button disabled={busy}>Save deadlines</Button></form>}
      {submission && <><p>Internal: {formatDate(submission.internal_due_at)} · Official: {formatDate(submission.official_due_at)}</p>{submission.items.map((item) => <label className="compact-row" key={item.id}><input type="checkbox" checked={item.checked} disabled={readOnly || Boolean(submission.submitted_at) || busy} onChange={(event) => run({ path: `submission/items/${item.id}/`, method: "PATCH", data: { checked: event.target.checked } })} /> {item.text}</label>)}<p className="muted">Revision {submission.revision} · Ready confirmations: {confirmationNames(submission.confirmations, submission.revision)}</p>{!readOnly && !submission.submitted_at && <Button variant="secondary" disabled={busy || submission.confirmations.some((c) => c.user === data.current_user && c.revision === submission.revision)} onClick={() => run({ path: "submission/confirm/", data: { revision: submission.revision } })}>Confirm I checked this submission</Button>}{submission.submitted_at && <div className="notice"><strong>Receipt recorded {formatDate(submission.submitted_at)}</strong><p>{submission.receipt_reference}</p>{submission.receipt_url && <a href={submission.receipt_url} target="_blank" rel="noopener noreferrer">Open submission receipt ↗</a>}</div>}</>}
      {!readOnly && !submission?.submitted_at && <form className="inline-form" onSubmit={(event) => submit(event, "submission/items/", (form) => ({ text: form.get("text") }))}><Field label="New submission check"><input name="text" required maxLength={300} /></Field><Button disabled={busy}>Add submission check</Button></form>}
      {manager && !readOnly && submission && !submission.submitted_at && <form className="form-grid" onSubmit={(event) => submit(event, "submission/receipt/", (form) => ({ receipt_url: form.get("receipt_url"), receipt_reference: form.get("receipt_reference") }))}><h4>Record the submission receipt</h4><p>Complete current tasks and checks, collect every active member's readiness confirmation, then submit through your university and record its receipt here.</p><Field label="Receipt or confirmation URL"><input name="receipt_url" type="url" maxLength={2048} /></Field><Field label="Submission reference"><input name="receipt_reference" maxLength={200} /></Field><Button disabled={busy}>Record receipt</Button></form>}
    </Panel>
    {isOwner && !readOnly && <Panel><h3>Private join links and approval</h3><p>Create a short-lived link for your intended teammates. Every join requires your approval.</p><form className="inline-form" onSubmit={(event) => submit(event, "join-links/", (form) => ({ expires_at: instant(form.get("expires_at")), max_uses: Number(form.get("max_uses")) }))}><Field label="Expires"><input name="expires_at" type="datetime-local" required min={toDateTimeLocal(new Date().toISOString())} /></Field><Field label="Maximum approved joins"><input name="max_uses" type="number" defaultValue={10} required min={1} max={50} /></Field><Button disabled={busy}>Create private join link</Button></form>{shareLink && <Field label="Copy this join link now"><input readOnly value={shareLink} onFocus={(event) => event.currentTarget.select()} /></Field>}{joins.error && <ErrorState error={joins.error} retry={() => void joins.refetch()} />}{joins.data?.links.map((link) => <div className="compact-row" key={link.id}><span>{link.uses}/{link.max_uses} joins · Expires {formatDate(link.expires_at)}{link.revoked_at && " · Revoked"}</span>{!link.revoked_at && <ConfirmAction triggerLabel="Revoke" triggerVariant="quiet" confirmLabel="Revoke link" message="Revoke this join link and reject its pending requests?" busy={busy} onConfirm={() => run({ path: `join-links/${link.id}/revoke/` })} />}</div>)}{joins.data?.requests.map((request) => <div className="compact-row" key={request.id}><span>{request.user.display_name} · Requested {formatDate(request.created_at)}</span><span className="row-actions"><Button disabled={busy} onClick={() => run({ path: `join-requests/${request.id}/resolve/`, data: { approve: true } })}>Approve member</Button><Button disabled={busy} variant="quiet" onClick={() => run({ path: `join-requests/${request.id}/resolve/`, data: { approve: false } })}>Reject</Button></span></div>)}</Panel>}
    {!readOnly && <Panel className="danger-zone"><h3>Leave this team</h3><p>Hand over your assigned tasks before leaving. The owner must also choose a successor.</p><Field label="Hand my current tasks to"><select value={handover} onChange={(event) => setHandover(event.target.value)}><option value="">Choose when you have assigned tasks</option>{others.map((member) => <option key={member.id} value={member.id}>{member.display_name}</option>)}</select></Field>{isOwner && <Field label="Next project owner"><select value={nextOwner} onChange={(event) => setNextOwner(event.target.value)}><option value="">Choose a successor</option>{others.map((member) => <option key={member.id} value={member.id}>{member.display_name}</option>)}</select></Field>}<ConfirmAction triggerLabel="Leave project" confirmLabel="Hand over and leave" message="Leave this project after handing over responsibilities? You will lose access to its private content." busy={busy} onConfirm={() => run({ path: "leave/", data: { handover_user: handover || null, new_owner: nextOwner || null } })} /></Panel>}
  </div>;
}
