# Generated by Django 5.2.17 on 2026-09-13 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCacheEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64)),
                ('cache_key', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'expires_at'], name='api_cache_provider_exp_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'cache_key'), name='unique_api_provider_cache_key'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('fetched_at'))), name='api_cache_expiry_after_fetch')],
            },
        ),
    ]
