# Generated by Django 5.2.17 on 2026-10-02 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(db_index=True, max_length=32)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_index', to='documents_store.projectdocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'tag'), name='unique_document_tag')],
            },
        ),
    ]
