# Generated by Django 5.2.17 on 2026-10-01 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('help', 'Help'), ('appeal', 'Appeal'), ('privacy', 'Privacy')], max_length=20)),
                ('subject', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=4000)),
                ('verification_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
